controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# hello:
#     path: hello
#     controller: App\Controller\helloController::hello

# helloName:
#     path: hello/{name}
#     controller: App\Controller\helloController::helloName